### ISSUE TITLE
[BUG] History tiles not working

### ISSUE THREAD

**Issue by giovi321** [resoai/TileBoard#804] opened 2021-12-25 17:22 UTC
I am having issues with HISTORY tiles all of a sudden. I keep getting an error message for all of them that I can partially read saying "ERROR IN REST API" "Code -1 retrieved for http://.....".
This happened all of a sudden, I'm running Home Assistant 2021.11.4,

This is my code:
```
               title: 'Temperature',
               width: 3,
               height: 3.7,
               items: [
         {
           position: [0, 0],
           width: 3,
           type: TYPES.HISTORY,
           id: 'sensor.livingroom_average_temperature',
           title: 'Average livingroom temperature',
/*           offset: 5*24*3600*1000,*/
           options: MINIMAL_CHART_OPTIONS,
         },
         {
           position: [0, 1],
           width: 3,
           type: TYPES.HISTORY,
           id: 'sensor.multisensor_bedroom_air_temperature',
           title: 'Bedroom temperature',
/*           offset: 5*24*3600*1000,*/
           options: MINIMAL_CHART_OPTIONS,
         },
         {
           position: [0, 2],
           width: 3,
           type: TYPES.HISTORY,
           id: 'sensor.multisensor_bathroom_air_temperature',
           title: 'Bathroom temperature',
/*           offset: 5*24*3600*1000,*/
           options: MINIMAL_CHART_OPTIONS,
         },
               ]
            },
     {
               title: 'Humidity',
               width: 3,
               height: 3.7,
               items: [
         {
           position: [0, 0],
           width: 3,
           type: TYPES.HISTORY,
           id: 'sensor.livingroom_average_humidity',
           title: 'Average livingroom humidity',
/*           offset: 5*24*3600*1000,*/
           options: MINIMAL_CHART_OPTIONS,
         },
         {
           position: [0, 1],
           width: 3,
           type: TYPES.HISTORY,
           id: 'sensor.multisensor_bedroom_humidity_3',
           title: 'Bedroom humidity',
/*           offset: 5*24*3600*1000,*/
           options: MINIMAL_CHART_OPTIONS,
         },
         {
           position: [0, 2],
           width: 3,
           type: TYPES.HISTORY,
           id: 'sensor.multisensor_bathroom_humidity',
           title: 'Bathroom humidity',
/*           offset: 5*24*3600*1000,*/
           options: MINIMAL_CHART_OPTIONS,
         },
               ]
            },
         ]
      },
```

**Comment by alphasixtyfive** [comment] 2021-12-26 13:00
I'm afraid it is a HA's issue. https://github.com/resoai/TileBoard/issues/386

**Comment by rchl** [comment] 2022-02-03 22:05
Duplicate of #386

**Closed by rchl** 2022-02-03 22:05 UTC
