### ISSUE TITLE
Items don't display on android 4.4.2

### ISSUE THREAD

**Issue by lruppert** [resoai/TileBoard#575] opened 2020-12-27 11:58 UTC
I have an old Android 4.4.2 phone I am trying to load a dashboard on, and it works fine right up until I add items, at which point none of it loads. Even adding an empty 'items: []' shortcircuits the loading process. (Before adding items, I get the red popup about authorization that comes from homeassistant refusing event access to non-administrator users. After adding items, I only get a blank page with the background colored.)

Is there a set of minimum requirements for this? I read in forums elsewhere that people are using this with old devices, including 4.4.2 so I assumed it would work for this too. But maybe it's modernized since then? I have other tileboards which work fine with desktop and newer android devices, which is what makes me wonder if it is an obsolescence thing...

Here is my config:
```
var CONFIG = {
   customTheme: CUSTOM_THEMES.MOBILE, // CUSTOM_THEMES.TRANSPARENT, CUSTOM_THEMES.MATERIAL, CUSTOM_THEMES.MOBILE, CUSTOM_THEMES.COMPACT, CUSTOM_THEMES.HOMEKIT, CUSTOM_THEMES.WINPHONE, CUSTOM_THEMES.WIN95
   transition: TRANSITIONS.SIMPLE, //ANIMATED or SIMPLE (better perfomance)
   entitySize: ENTITY_SIZES.SMALL, //SMALL, BIG are available
   tileSize: 150,
   tileMargin: 5,
   serverUrl: 'https://' + location.hostname,
   wsUrl: 'wss://' + location.hostname + '/api/websocket',
   authToken: null, // Not really, but lets pretend
   debug: true, // Prints entities and state change info to the console.
   pingConnection: true, //ping connection to prevent silent disconnections

   // next fields are optional

   pages: [
      {
         title: "Home",
         header: DEFAULT_HEADER,
         groups: [
           {
             title: 'Group title',
             width: 1,
             height: 1,
             groupMarginCss: '5px 5px',
             items: [  ],
           },
         ]
      },
   ],
}
```

**Comment by alphasixtyfive** [comment] 2020-12-30 23:15
Most likely the problem is with HA’s authentication which does not work with WebView which was shipped back in the days of Android 4.x. You can try specifying a long lived token to overcome it but be careful and not expose that device via internet.

**Comment by DeviousPenguin** [comment] 2020-12-31 01:31
I have had similar issues on older iOs 9.x devices in the past, I found that posting an error log in the 'ha frontend' repo here https://github.com/home-assistant/frontend was able to resolve the issue.

**Comment by rchl** [comment] 2021-02-15 20:33
There is not enough information here to solve the issue.

The issue with iOS 9.x was fixed in HA so authentication page loads properly now.

For the android issue, I'd need to see the actual error to know more. Using the latest version of TileBoard should hopefully show the exception when trying to load the page.

We can re-open if we get more information.

**Closed by rchl** 2021-02-15 20:33 UTC

**Comment by sergeolkhovik** [comment] 2022-03-29 11:05
If that's still possible, I'd like to activate this issue. I have some old tablet running 4.4.2 and thinking about having any dashboard on it (trying TB and AD HADashboard, but none of them works), the idea is to run WallPanel (not a simple browser), but neither WallPanel, nor built-in (i.e. Chrome 30) show the dashboard, only an empty screen with some background). I'm able to connect to the tablet's browser from desktop Chrome and see the console, there's an error:
```
TypeError
message: "Invalid attempt to iterate non-iterable instance.↵In order to be iterable, non-array objects must have a [Symbol.iterator]() method."
stack: "TypeError: Invalid attempt to iterate non-iterable instance.↵In order to be iterable, non-array objects must have a [Symbol.iterator]() method.↵    at Uh (http://tb.o-nest/scripts/app-e56cc452.js:1:40967)↵    at sx (http://tb.o-nest/scripts/app-e56cc452.js:414:53697)↵    at http://tb.o-nest/scripts/app-e56cc452.js:414:55892↵    at new <anonymous> (http://tb.o-nest/scripts/app-e56cc452.js:414:55981)↵    at Object.invoke (http://tb.o-nest/scripts/app-e56cc452.js:7:26451)↵    at D.instance (http://tb.o-nest/scripts/app-e56cc452.js:7:60503)↵    at at (http://tb.o-nest/scripts/app-e56cc452.js:7:51398)↵    at http://tb.o-nest/scripts/app-e56cc452.js:7:44950↵    at http://tb.o-nest/scripts/app-e56cc452.js:7:44967↵    at http://tb.o-nest/scripts/app-e56cc452.js:7:44967"
__proto__: Error
 [angular.js:15697](http://tb.o-nest/node_modules/angular/angular.js)
(anonymous function)
```
Can that be helpful to identify the problem and possibly fix it?
TB is 2.9.0 running under nginx virtual host (/etc/nginx/sites-enabled/tileboard):
```
server {
        listen 80;
        listen [::]:80;

        # server_name _;
        server_name tb.o-nest;

        charset   utf-8;
        root /home/homeassistant/www/tileboard;
        index index.html;
        location ~ /\.ht {
                deny all;
        }

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }
```
and here's my very simple configuration:
```
/*
 This is an example configuration file.

 COPY OR RENAME THIS FILE TO config.js.

 Make sure you use real IDs from your HA entities.
*/

var CONFIG = {
   tileSize: 150,
   tileMargin: 6,
   authToken: 'x....',
   events: [],
   timeFormat: 24,
   onReady: function () {},

   header: { // https://github.com/resoai/TileBoard/wiki/Header-configuration
      styles: {
         margin: '30px 130px 0',
         fontSize: '28px'
      },
      right: [
         {
            type: HEADER_ITEMS.CUSTOM_HTML,
            html: 'MyCity'
         },
      ]
   },
   pages: [
      {
         title: 'Головна',
         bg: 'images/bg1.jpeg',
         icon: 'mdi-home-outline', // home icon
         groups: [
            {
               title: '',
               width: 4,
               height: 3,
               items: [
                  {
                     position: [0, 0],
                     width: 2,
                     title: 'Short instruction',
                     type: TYPES.TEXT_LIST,
                     list: [
                        {
                           title: 'Read',
                           icon: 'mdi-numeric-1-box-outline',
                           value: 'README.md'
                        },
                        {
                           title: 'Ask on forum',
                           icon: 'mdi-numeric-2-box-outline',
                           value: 'home-assistant.io'
                        },
                        {
                           title: 'Open an issue',
                           icon: 'mdi-numeric-3-box-outline',
                           value: 'github.com'
                        },
                     ]
                  },
               ]
            },
         ]
      }
   ],
}
```

Thanks!

**Comment by rchl** [comment] 2022-03-29 11:21
Looks like the error is within the Angular.js framework itself so I don't think that we can do much about it.

I'd suggest that you look into upgrading the firmware in your tablet to something never. There might be some unofficial ways to get a later firmware into it.
