### ISSUE TITLE
no answer after resume

### ISSUE THREAD

**Issue by madmicio** [resoai/TileBoard#203] opened 2019-02-14 16:53 UTC
I'm using tilebord on a dedicated tablet. I use kiosk browser, but I have the same problem on other devices and chorme.
when I load the page for the first time, everything works correctly. when the device goes into standby and I resume tilebord, it does not seem to be connected to home assistant. no command works until the page is reloaded.
depends on what?  is There a solution?

**Comment by resoai** [comment] 2019-02-14 17:32
Make sure tablet does not disconnect WiFi when it goes to standby.

**Comment by Evgeny-** [comment] 2019-02-14 17:40
Try to update repo and use `reconnectAfterScreensaver: true` in the root of config

**Comment by madmicio** [comment] 2019-02-19 18:52
in the config.js file like this?
/*
 This is an example configuration file.

 COPY OR RENAME THIS FILE TO config.js.

 Make sure you use real IDs from your HA entities.
*/
   reconnectAfterScreensaver: true,
var CONFIG = {
   customTheme: CUSTOM_THEMES.TRANSPARENT etc.etc.etc.

**Comment by Evgeny-** [comment] 2019-02-20 05:41
@madmicio 

```
var CONFIG = {
   reconnectAfterScreensaver: true,
   customTheme: CUSTOM_THEMES.TRANSPARENT,
.......
```

**Comment by rchl** [comment] 2019-02-20 20:21
I have the same issue sometimes on my phone. TileBoard installed on desktop as an "app". After resume I get one of those behaviors:
- "System error" notification
- Invalid token notification (can't remember exact message)
- Just empty app background with no entities

In most of those cases I get error notification and then entities appear after short while. In rare cases waiting doesn't seem to help and I need to reload page.

I have disabled screensaver so this change (11f626cdcf7267235081e67d80e3160e2f9270f1) wouldn't even have a chance to help. But looking at this change, it seems like quite a hack. Is there specifying reasoning behind it? It seems quite weird to try to reconnect on *showing screensaver*. Is the idea that this code should trigger after resume because then all queued actions would trigger that didn't have a chance to run during sleeping? But why not do it on hiding screensaver then?

Anyways, maybe it would be useful to just analyze with logs what exactly happens (websocket connection status and such) on all of those cases and try to find more specific solution? I could do job myself if you are interested.

**Comment by Evgeny-** [comment] 2019-02-23 05:12
@rchl i probably get this issue wrong. For some reason i thought about screensaver. So i did incorrect fix. Tbh i don't know how to solve your common problem. May be we should try to use some analog of ping.

**Comment by madmicio** [comment] 2019-03-01 17:30
really frustrating!tileboard is the perfect solution for me!graphically functional!but this connection problem is driving me crazy.I have come to this point. to avoid problems I decided to keep the screen always on and to minimize the brightness after a few seconds of activity.but having a tablet with double tap to resume and not being able to use it is really frustrating!

**Comment by Evgeny-** [comment] 2019-03-02 06:06
@madmicio i've tried to make a ping connection. Now script basically trying to pull user data every 5 seconds (and on focus). Some devices don't send any events when they close socket connection, so ping was only solution i found. Though i wasn't able to catch silent disconnect in my devices, so please test new version and comment if it's helped.

https://github.com/resoai/TileBoard/commit/9b4af30276ed27f986b4db4e870c53a5fbc51247

**Comment by madmicio** [comment] 2019-03-03 13:55
![tileboard](https://user-images.githubusercontent.com/42836292/53696124-59251e80-3dc4-11e9-9a8c-cda1019c07cf.JPG)

**Comment by madmicio** [comment] 2019-03-03 14:00
[2.zip](https://github.com/resoai/TileBoard/files/2923179/2.zip)

**Comment by Evgeny-** [comment] 2019-03-03 15:28
I dunno. Try to use long-lived token 
https://github.com/resoai/TileBoard/blob/master/config.example.js#L18

**Comment by apop880** [comment] 2019-03-04 18:56
I've recently started seeing a related issue as well. After some length of time (not yet sure exactly how long but I tested after about 5 hours today and got a failure, could be less than that even, though), the connection seems to be lost. I never turn my screen off but do use the screensaver. The weather sensor on there eventually quits updating and when I tap to exit the screensaver it returns to a blank screen and my header and tiles are gone. This just started recently and I do have the latest TileBoard code.

**Comment by madmicio** [comment] 2019-03-04 21:26
in congif:
no screen saver
pingMaxTimeout: 3000,
transition: TRANSITIONS.SIMPLE,

in my asus zenpad 10:
fully kiosk with:
auto reload on network reconnect     ...ON
auto reload on internet reconnect     ...ON
set CPU kakelock                                ...ON
set WIFI kakelock                                ...ON

tasker:
reconnect network every 5 min.
ping my https url every 2 min.

the situation seems to have improved, but I do not know if it's just a suggestion or luck.
now 80% work ok
20% black screen up to the reload

**Comment by apop880** [comment] 2019-03-05 03:41
In my case, I'm hopeful this was actual an issue on my end. I think I've actually lined up the start of the issue to when I switched Wi-Fi routers, and I think there was maybe an issue with the Kindle and the new router. I've now got a static IP assigned to the Kindle and it seems stable so far, knock on wood.

**Comment by Evgeny-** [comment] 2019-03-05 06:09
Have you tried constant `authToken` ?

**Comment by madmicio** [comment] 2019-03-05 18:38
yes `authToken` set.


I'm doing some tests to rule out any causes.
in the tasker I set a profile that every 2 minutes turns on the monitor, ping 8.8.8.8.
if the ping response is good then simply display on the screen: "network connected" if the response to ping is: "100% packages lost ", tasker disconnects and reconnects the wifi connection.


the result is that tasker turns on the screen and tells me that in fact the device is connected. but random I get black screen

**Comment by apop880** [comment] 2019-03-06 03:14
Hey guys, I just forked the repository and committed a couple of changes to api.js and main.js. @madmicio would you mind trying it out and seeing if it's any more stable for you? It seems to be better for me so far but I'd like to get some more people testing it before I submit a PR.

**Comment by madmicio** [comment] 2019-03-06 11:11
where I can find the new files?

**Comment by apop880** [comment] 2019-03-06 14:21
@madmicio My forked repo is here: https://github.com/apop880/TileBoard - however, I'm still seeing some issues in my testing. If you want to give my changes a try you really only need to grab /scripts/models/api.js and scripts/controllers/main.js. However, I'm probably going to push some more changes tonight after I test some more so you may want to hold off until then.

**Comment by madmicio** [comment] 2019-03-06 19:21
![screenshot_2019-03-06-19-53-20](https://user-images.githubusercontent.com/42836292/53907336-3fe2d300-404d-11e9-8701-a2ff40fccc2b.jpg)

random: screen of tileboard, black screen and this message

**Comment by apop880** [comment] 2019-03-06 19:42
Thanks for the screenshot, I'll keep working on it on my end and let you know when I have something to retest.

**Comment by apop880** [comment] 2019-03-07 03:17
Made another commit to my repo. @madmicio feel free to grab the latest changes I made to main.js. I temporary halted the pinging until the connection is re-established. So far so good after testing from my computer so I could see some actual logging. If the connection remains stable overnight I'll put in the PR tomorrow.

**Comment by apop880** [comment] 2019-03-07 14:27
Didn't work for me overnight. Going to keep trying things but it might be a few days.

**Comment by madmicio** [comment] 2019-03-07 14:59
![img_20190307_143509](https://user-images.githubusercontent.com/42836292/53965710-fd270680-40f1-11e9-9cd5-d4633e008279.jpg)
![img_20190307_143510](https://user-images.githubusercontent.com/42836292/53965721-ff896080-40f1-11e9-8482-744346bb49b7.jpg)
on ipad2

**Comment by madmicio** [comment] 2019-03-07 15:00
![img_20190307_143524](https://user-images.githubusercontent.com/42836292/53965744-0d3ee600-40f2-11e9-9174-4467e8380979.jpg)
on zenpad 10

**Comment by madmicio** [comment] 2019-03-07 15:01
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2605)
2019-03-07 15:22:32 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.254
2019-03-07 15:22:32 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.254
2019-03-07 15:22:32 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.254
2019-03-07 15:36:12 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal error on transport TCPTransport (error status in uv_stream_t.read callback)
TimeoutError: [Errno 110] Operation timed out
2019-03-07 15:36:12 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal error on transport TCPTransport (error status in uv_stream_t.read callback)
TimeoutError: [Errno 110] Operation timed out
2019-03-07 15:36:17 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal error on transport TCPTransport (error status in uv_stream_t.read callback)
TimeoutError: [Errno 110] Operation timed out
2019-03-07 15:36:17 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal error on transport TCPTransport (error status in uv_stream_t.read callback)
TimeoutError: [Errno 110] Operation timed out
2019-03-07 15:55:14 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal error on transport TCPTransport (error status in uv_stream_t.read callback)
OSError: [Errno 113] Host is unreachable

**Comment by apop880** [comment] 2019-03-07 15:52
I've seen some of the same error messages though I haven't been able to definitely tie them all to anything going on in TileBoard. The fact that you're actually seeing "Reconnection successful" toasts is somewhat encouraging, and maybe at least a step in the right direction. I'll keep at it. Thanks for the screenshots and additional testing.

**Comment by madmicio** [comment] 2019-03-07 22:36
when I get this error in the log:
```
2019-03-07 23:26:04 WARNING (MainThread) [aiohttp.websocket] websocket connection is closing.
2019-03-07 23:26:22 WARNING (MainThread) [aiohttp.websocket] websocket connection is closing.
```

at the same time in tilebord on my pc, I could see the connection problems and the subsequent reconnection

**Comment by madmicio** [comment] 2019-03-07 23:04
in fact, these websockket closures occurred when I checked the configuration in the home assistant interface. the configuration was wrong and home assistant returned the error. in that exact moment the websocket was closed. I tried again for confirmation and the same thing happened.

**Comment by madmicio** [comment] 2019-03-08 09:39
```
OSError: [Errno 113] Host is unreachable
2019-03-08 10:37:18 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.254
2019-03-08 10:37:24 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection.1855718896] Auth message incorrectly formatted: extra keys not allowed @ data['id']. Got 976
not a valid value for dictionary value @ data['type']. Got 'ping'
2019-03-08 10:37:24 ERROR (MainThread) [homeassistant.core] Error doing job: SSL error errno:1 reason: KRB5_S_INIT
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 504, in uvloop.loop.SSLProtocol.data_received
  File "uvloop/sslproto.pyx", line 204, in uvloop.loop._SSLPipe.feed_ssldata
  File "uvloop/sslproto.pyx", line 189, in uvloop.loop._SSLPipe.feed_ssldata
  File "/usr/local/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2605)``
```

**Comment by apop880** [comment] 2019-03-08 15:23
Strange, those are not the same errors I'm seeing. I'm going to keep looking. Worst case scenario, if I can't figure this out, I'm going to code in an option to refresh the page if the socket connection is lost. A little bit of a hack but should be reliable at least.

**Comment by apop880** [comment] 2019-03-13 13:29
@madmicio I finally had a chance to get back to this and make some code changes. I've pushed an updated version of main.js to my forked repo, go ahead and test it when you have a chance. It definitely seems to have fixed my issue with disconnects, as I've had a session running for 10+ hours without any issues reconnecting. Hopefully it will do the same in your scenario, and then I can clean up a couple things with my code and get the PR submitted.

**Comment by madmicio** [comment] 2019-03-14 16:22
testing….
I'm trying to change tablet. with the new main.js the wifi connection often goes haywire. and I have to restart the wifi. when instead the connection remains stable and I log in after a long period to tilebord seems to see a timelapse

**Comment by apop880** [comment] 2019-03-14 16:26
> testing….
> I'm trying to change tablet. with the new main.js the wifi connection often goes haywire. and I have to restart the wifi.

I'm not sure I follow. The changes to main.js shouldn't be affecting your wifi connection.

> when instead the connection remains stable and I log in after a long period to tilebord seems to see a timelapse

Can you elaborate on this?

**Comment by madmicio** [comment] 2019-03-14 20:24
> I'm not sure I follow. The changes to main.js shouldn't be affecting your wifi connection.

> 
I'm sure it's a tablet problem.

> Can you elaborate on this?

> sometimes, when I turn on the dislay, I see all the actions, taken during the tablet standby, fast scrolling, very fast. on-off lights, sensors that change values ​​quickly, device tracker quickly updates etc etc.

**Comment by apop880** [comment] 2019-03-14 21:16
> sometimes, when I turn on the dislay, I see all the actions, taken during the tablet standby, fast scrolling, very fast. on-off lights, sensors that change values ​​quickly, device tracker quickly updates etc etc.

When TileBoard first connects/reconnects to the WebSocket, it requests the current states of all components. So, it sounds like it's just getting the updated states for everything and then updating them all. That would be expected behavior.

Does the ping/reconnect functionality seem to be working any better for you?

**Comment by resoai** [comment] 2019-04-03 15:49
Should we close this one?

**Comment by apop880** [comment] 2019-04-03 18:02
I personally think we can.

**Closed** 2019-04-03 18:11 UTC

**Comment by utech-git** [comment] 2020-09-04 13:15
Guys, i'm having the exact same problem with my tablet + tileboard + fully kiosk browser.

I read the whole thread but I didn't got clear to me what was done or what am i supposed to do.
Did your changes made into the official release, @apop880 ???

Just to clarify: a few minutes after my tablet turns the screen off it seems that tileboard loses connection with HA. So when the screen turns back on the tileboard interface stops responding for a moment. Sometimes it shows messages of ping unsuccessful then successfull reconection. All the tiles blinks and then it is responding again.

I managed to make it "less worse" but reloading the page via API or remote admin from time to time. Even with screen off it works. The problem is: after the reload, when I turn the screen on again the tiles are gone and it takes about 1/2 second for they to appear again. (it is faster then when I'm not using reload).

I can't use long lived auth token because my HA is exposed on the internet.

(sorry to reopen the issue. But I think it's better than opening a new one for the same problem)

**Comment by cgarwood** [comment] 2020-09-04 13:26
@utech-git Check Fully's settings -> Advanced Web Settings -> Pause Webview while in Background (experimental) and make sure it's toggled off. That got included in a Fully Kiosk Browser update a couple versions ago and caused me a bunch of trouble.

**Comment by utech-git** [comment] 2020-09-05 23:00
Thanks, but it was already disabled =/

**Comment by rchl** [comment] 2020-09-06 06:55
TileBoard communicates with Home Assistant through a persistent websocket connection and I'd say that it's pretty much expected that this connection is is interrupted when tablet or phone goes to sleep (tablet might remove the browser from memory or just the browser might suspend the tab for performance reasons). The only thing that could be done here is to improve the experience when that happens IMO.

(I guess you could also search in Android options for something that would allow to disable memory optimizations for specific apps but the browser/web view itself might have some optimizations of its own also.)

**Comment by resoai** [comment] 2020-09-06 07:06
One thing that could potentially be done from our side is to detect first reconnect and try to do it silently.

**Comment by rchl** [comment] 2020-09-06 07:48
I think we can definitely improve the visual experience when reconnecting but we should make it clear that it will likely not improve the time it takes to reconnect after waking up from sleep.

**Comment by resoai** [comment] 2020-09-06 08:35
How about dimming the whole page just a tiny bit on the first reconnect?

**Comment by rchl** [comment] 2020-09-06 09:05
Let's discuss this in https://github.com/resoai/TileBoard/issues/420 as this issue was about something else (not reconnecting at all).
