### ISSUE TITLE
0.107.1 The websocket command 'camera_thumbnail' has been deprecated.

### ISSUE THREAD

**Issue by radinsky** [resoai/TileBoard#351] opened 2020-03-21 17:46 UTC
After upgrading to 0.107.1 getting errors as following:
(If I disable tileboard, the error stops)

```
2020-03-21 19:42:49 WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated.
2020-03-21 19:42:49 WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated.
2020-03-21 19:42:49 WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated.
2020-03-21 19:42:52 WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated.
2020-03-21 19:42:56 WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated.
2020-03-21 19:42:59 WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated.
2020-03-21 19:43:03 WARNING (MainThread) [homeassistant.components.camera] The websocket command 'camera_thumbnail' has been deprecated.
```

**Comment by resoai** [comment] 2020-03-21 18:11
Well, the error message is self-explanatory, `camera_thumbnail` is being deprecated by HA and shall be dropped in future releases. You have to use `CAMERA` or `CAMERA_STREAM` tile.

**Comment by LaBoss** [comment] 2020-06-01 11:29
Viva, is there an alternative?

I changed my tileboard to CAMERA and CAMERA_STREAM, the error disappears, but the problem is that my tablet closes the application after a while! I think it runs out of memory after 1 hour with the stream running.

With camera_thumbnail it's been 5 days without going down

**Comment by resoai** [comment] 2020-07-01 09:44
This is now fixed. pleas grab the latest code and switch `CAMERA` or `CAMERA_STREAM` tile.

**Comment by LaBoss** [comment] 2020-07-01 11:18
> This is now fixed. pleas grab the latest code and switch `CAMERA` or `CAMERA_STREAM` tile.

Thanks, updated, testing now

**Closed** 2020-09-04 21:08 UTC

**Comment by rchl** [comment] 2020-11-27 21:31
FYI: In https://github.com/resoai/TileBoard/releases/tag/v2.1.1 the CAMERA_THUMBNAIL type was removed and replaced with CAMERA.
