### ISSUE TITLE
Feature Request: Cover Support

### ISSUE THREAD

**Issue by vpnmaster** [resoai/TileBoard#14] opened 2018-06-20 15:45 UTC
I think it's not so hard to implement. We only need UP, STOP, DOWN buttons calling cover.open_cover, cover.stop_cover, cover.close_cover services.

![1](https://user-images.githubusercontent.com/4130346/41669151-cc300018-74b9-11e8-9790-dc156c479998.png)

or

![2](https://user-images.githubusercontent.com/4130346/41669165-d3f91816-74b9-11e8-9380-f396ee6d331b.png)

In case you don't own a cover hardware, template cover is a good option.
https://www.home-assistant.io/components/cover.template/

**Comment by resoai** [comment] 2018-06-20 15:47
Do you know how one looks like in HaDashboard?

**Comment by vpnmaster** [comment] 2018-06-20 15:51
Sorry, I'm not using HADashboard.

**Comment by resoai** [comment] 2018-06-22 16:11
Could you please tell which cover do you have? Does it report the state i.e. open, closed?

**Comment by avandeputte** [comment] 2018-06-25 01:54
Seconding the enhancement request...
My cover is myq,  it reports states of Open and Closed.

![image](https://user-images.githubusercontent.com/20116257/41826613-db80a896-77f8-11e8-9642-4939c9b8be27.png)

I hope this helps!

**Comment by resoai** [comment] 2018-06-25 17:07
I might have implemented it. Could you please check? 

```
                  {
                     position: [2, 3],
                     type: TYPES.COVER,
                     title: 'Garage door',
                     id: 'cover.garage_door'
                     states: {
                        open: 'Open',
                        closed: 'Closed'
                     }
                  }
```

**Comment by resoai** [comment] 2018-06-25 17:12
If it works, would you be so kind to post which states HA is reporting while cover is opening and closing?

**Comment by vpnmaster** [comment] 2018-06-25 18:06
Not working for me.
HA gives me 'Unable to find service cover/cover_close' in error log.
I believe the right services are those in my first post (HA ver 0.72)

**Comment by resoai** [comment] 2018-06-25 18:16
No, it is stop_cover, open_cover and close_cover. I (somehow) had it as cover_open, cover_close etc. Could you please check now?

**Comment by vpnmaster** [comment] 2018-06-25 18:30
All commands are working now.
My somfy covers aren't reporting the state so I can't confirm if this part is working.

**Comment by resoai** [comment] 2018-06-25 18:31
I thought perhaps if you stop it half-way we could show "Open 50%" or something like this.

**Comment by vpnmaster** [comment] 2018-06-25 18:34
I think that we will have a problem when someone open or close the cover from the official front end

**Comment by resoai** [comment] 2018-06-25 18:35
Why? We are listening to all events and are updating state whenever HA reports it

**Comment by vpnmaster** [comment] 2018-06-25 18:45
In my case the covers always reporting unknown state. Also they have their own remote control...
If you want to enhance this tile you can add a similar slider like lights for cover.set_cover_position service. I found many posts in forum where people ask for this slider in the official front end.

**Comment by resoai** [comment] 2018-06-25 18:47
I'd be happy to do it but since yours doesn't even report a state, it will be hard to know it even works :) 

On a separate note, I don't particularly like the way the tile looks, perhaps you have seen other dashboards that have it implemented more visually pleasing?

**Comment by vpnmaster** [comment] 2018-06-25 18:54
Let's see what other users have to say about this tile.
Personally, I'm very happy with it.

**Comment by avandeputte** [comment] 2018-06-25 21:15
Tested - worked great.  
- My cover does report state,  and that works fine.
- There is no state change reported while the door is opening or closing.
- Also my cover doesn't appear to support stop_cover, so I can't test that part.

Very happy about this tile as well!

**Comment by resoai** [comment] 2018-06-25 21:22
Can you please post the attributes? It should have supported_features filed (a long integer).

**Comment by avandeputte** [comment] 2018-06-25 23:06
Here are the attributes from the developer console:

Attributes:{friendly_name: "Garage Door", supported_features: 11, device_class: "garage"}
entity_id:"cover.garage_door_opener"
last_changed:"2018-06-25T23:03:35.648164+00:00"
last_updated:"2018-06-25T23:03:35.648164+00:00"
state:"closed"

**Comment by resoai** [comment] 2018-06-25 23:08
Not that many. Adding tilt position should not be very difficult but we need someone who could test it.

**Comment by resoai** [comment] 2018-06-26 02:13
Yeah and perhaps motorized curtains :)

**Comment by resoai** [comment] 2018-06-27 16:51
I've added some code to  disable open button when cover is open and close when it is closed. Could you please confirm it works OK?

**Comment by resoai** [comment] 2018-06-27 23:02
OK, it has been confirmed to be working.

**Closed by resoai** 2018-06-27 23:02 UTC
Labels: enhancement
