### ISSUE TITLE
Browser randomly closes

### ISSUE THREAD

**Issue by BrettWa** [resoai/TileBoard#308] opened 2019-11-28 12:08 UTC
Not 100% sure if this is an issue with TileBoard, or something else. I run the latest version on HA running in a docker container.

I then have  a wall mounted iPad displaying TileBoard - since the 0.102 version of HA - the browser on the iPad just closes completely, ending up back at the home screen?

Is there something obvious I can check, or a log that'll tell me what/why it happens? I have a very basic layout at this stage. Couple of switches/lights, camera view, weather, and single media player.

**Comment by AalianKhan** [comment] 2019-11-28 12:35
Try using inspect tools in chrome by clicking CTRL + SHIFT + I. Go to the console and you will see logs in there. Did this happen on chrome too? Which app are you using?

**Comment by BrettWa** [comment] 2019-11-28 12:37
It's quite frequent on the iPad, say every 2 hours randomly. 

I've actually had TileBoard open on chrome this morning, hasn't closed yet - and no errors from the console. It's why I was hoping there'd be some way of turning on logging.

Not sure what you mean by which app?

**Comment by AalianKhan** [comment] 2019-11-28 12:43
App as an browser. Some apps when they encounter am error just close the app and other like chrome just refresh the page. The logs for tile board are found by using Dev tools on the browser in chrome you press CRTL + SHIFT + I  to go to the dev tools. Then there will be a tab near the top called console. There you will see logs of tile board and any error that's occuring. Do you have screensaver enabled?

**Comment by BrettWa** [comment] 2019-11-28 12:47
Ah - sorry - using safari on the iPad - and no screensaver - its always up as a dashboard, and was fine until the latest version of HA, also - nothing new, or changed on the iPad.

I've had the console open on Chrome on my laptop since this morning - but - no errors yet.

**Comment by AalianKhan** [comment] 2019-11-28 12:57
So from what I understand the whole safari closes when tile board is running. Try using this method to see where happening on safari https://medium.com/@mattcroak718/debugging-your-iphone-mobile-web-app-using-safari-development-tools-71240657c487

**Comment by BrettWa** [comment] 2019-11-28 12:58
Yes - that's exactly what happens. 

Don't use Apple at all - so the above link will help quite a bit, thanks.

**Comment by AalianKhan** [comment] 2019-11-28 13:01
There is also an app called kiosk pro lite. It uses the full screen instead of showing the headers and other navigation buttons

**Comment by BrettWa** [comment] 2019-11-28 13:04
I'll give that a try as well - maybe it behaves.

I currently achieve the same (no headers, etc) - by saving the bookmark to the homescreen, when opened from there, it doesn't display navigation

**Comment by rchl** [comment] 2019-11-29 11:57
If it just closes it could be it's running out of memory. Maybe there is a leak in the new version of TileBoard.

It would be hard to debug something that is just closing so I'm not sure suggestions above would help you with that.

**Comment by BrettWa** [comment] 2019-11-30 12:55
Finally found the cause, when ever I use the camera thumbnail - it closes Safari after while.

This is the code, was running fine:
```
{
  position: [1, 1],
  id: 'camera.driveway_cam',
  type: TYPES.CAMERA_THUMBNAIL,
  bgSize: 'cover',
  width: 1,
  state: false,
  fullscreen: {
     type: TYPES.CAMERA,
     refresh: 1500, // can be number in milliseconds
     bgSize: 'contain'
  },
  refresh: function () { // can also be a function
     return 3000 + Math.random() * 1000
  }
}
```

**Comment by AalianKhan** [comment] 2019-12-04 21:03
can you mark the issue closed, please?

**Comment by rchl** [comment] 2019-12-04 21:26
To be fair, we could still try to figure out if TileBoard can do something for that issue.

As far as I can see by looking at the code, all TileBoard does it re-creates an element with new background image on each `refresh`. It looks like it properly cleans up old element so there doesn't seem to be any leak there.

If the browser has some bug that causes it to leak then that would explain the crash but nothing we could do about it. Is that up-to-date Safari version or something ancient?

**Comment by BrettWa** [comment] 2019-12-05 09:23
It seems to be something with Tileboard + Safari browser + the above Camera Thumbnail. I did notice a red "SYSTEM ERROR" popup on Tileboard once or twice, but it didn't force close the browser.


On Chrome on my laptop - the window stays open with no errors.


If there's no apparent fix - I can close the issue?

**Closed** 2020-02-25 02:26 UTC

**Comment by Romkabouter** [comment] 2021-01-31 10:53
Hi there, I have encountered this issue as well, so it might be a good idea to reopen?

**Comment by rchl** [comment] 2021-01-31 14:38
We don't have enough information to reproduce so it wouldn't make sense to reopen if we can't do anything about it.

If you can figure out what causes it and if it's specific to certain tiles then we can reopen and try to fix it then.

**Comment by Romkabouter** [comment] 2021-01-31 17:18
Well, If you have one page with a camera_thumbnail on IOS 9.3.5 safari, the browser will crash at some point in time.
This is reproducable.
I have remove the tile from my dashboard and have to wait and see if indeed this tile is the issue.
If that does not crash the browser, I think the issue is in the refresh part due to adding and removing a div in the appendImage function. I saw you can disable the refresh and then it does not call that function.

So, my next step when removing the camera_thumbail does not crash the browser anymore is to disable the refresh.

Also, in my opinion the disability to solve it does not make it a non-issue. The original topic is browser randomly closes, which is still an issue. 

Do you know if there is a specific reason do remove and add the div inside the refresh function?

**Comment by rchl** [comment] 2021-01-31 18:16
> Well, If you have one page with a camera_thumbnail on IOS 9.3.5 safari, the browser will crash at some point in time.

This is with the latest TileBoard version?
In the latest version, the CAMERA_THUMBNAIL tile is removed and automatically mapped to CAMERA so I wonder if we are talking about the same code.

CAMERA tile also adds and removes div on each refresh.

It could be that there is some bug in that old Safari version that causes a leak so if that's the case, we'd need a workaround of some sort.

**Comment by Romkabouter** [comment] 2021-01-31 18:36
Hmm, I have missed that release indeed. 
I will try it with the CAMERA tile and see if that issue is also occuring with that tile. Refresh interval was set to 2000 (2 seconds)

Point of actions for me:
- wait a day to see if indeed the (old) caused the crashes.
- change CAMERA_THUMBAIL to CAMERA with a refresh and see if the browser crashes. If not, all is ok. If it does, check without refresh set.

I see an opacity transition indeed. If the issue still occurs in the CAMERA tile, maybe I can find some sort of workaround :)

**Comment by Romkabouter** [comment] 2021-02-02 08:29
I can confirm that a tileboard with only 3 light tiles works properly. It ran without issue for 2 days.
Now I will add a CAMERA without a refresh (refresh: false)
