### ISSUE TITLE
Light in TileBoard red in HomeKit Theme

### ISSUE THREAD

**Issue by timtim8461** [resoai/TileBoard#502] opened 2020-10-26 18:31 UTC
Hi,
I just started with TileBoard. I used CUSTOM_THEMES.HOMEKIT as Theme, but the Tile is red when enabled (not white like on the Screenshots in Readme).

Is that supposed to be like that, or am I missing something?

<img width="202" alt="image" src="https://user-images.githubusercontent.com/10117610/97213344-c8355f00-17c1-11eb-906a-b1e66f7ac1df.png">

**Comment by rchl** [comment] 2020-10-26 18:52
A bug https://github.com/resoai/TileBoard/issues/448

**Comment by rchl** [comment] 2020-10-29 19:50
Duplicate of #448

**Closed by rchl** 2020-10-29 19:50 UTC
